"""Pydantic v2 request/response schemas, split by domain to mirror app.models."""

from app.schemas.alumni import (
    AlumniProfileOut,
    AlumniProfileUpdate,
    JobPostCreate,
    JobPostOut,
    JobPostUpdate,
)
from app.schemas.e2ee import (
    DeviceCreate,
    DeviceOut,
    DevicePrekeyBundleOut,
    OneTimePrekeyCreate,
    OneTimePrekeyOut,
    PrekeyBundleOut,
    PrekeyCountOut,
    PrekeyUpload,
    PrekeyUploadRequest,
    SignedPrekeyCreate,
    SignedPrekeyOut,
)
from app.schemas.finance import (
    DuesCycleCreate,
    DuesCycleOut,
    LedgerEntryCreate,
    LedgerEntryOut,
    SpendApprovalCreate,
    SpendApprovalDecision,
    SpendApprovalOut,
    SpendApprovalUpdate,
)
from app.schemas.identity import (
    CampusOut,
    ChapterCreate,
    ChapterInviteCreate,
    ChapterInviteOut,
    ChapterJoin,
    ChapterJoinRequest,
    ChapterOut,
    ChapterUpdate,
    MembershipOut,
    MembershipUpdate,
    UserCreate,
    UserOut,
    UserUpdate,
)
from app.schemas.lineage import (
    FamilyCreate,
    FamilyOut,
    LineageEdgeCreate,
    LineageEdgeOut,
    LineageNodeOut,
    LineageTreeOut,
)
from app.schemas.meetings import (
    MeetingAttendanceItem,
    MeetingAttendanceOut,
    MeetingAttendanceUpdate,
    MeetingCreate,
    MeetingOut,
    MeetingUpdate,
)
from app.schemas.messaging import (
    ConversationCreate,
    ConversationMemberOut,
    ConversationOut,
    MessageCreate,
    MessageOut,
    MessageReceiptCreate,
    MessageReceiptOut,
)
from app.schemas.social import (
    PostCommentCreate,
    PostCommentOut,
    PostCreate,
    PostLikeOut,
    PostOut,
    PostUpdate,
)
from app.schemas.yak import (
    ContentReportCreate,
    ContentReportOut,
    UserBlockCreate,
    UserBlockOut,
    YakCreate,
    YakOut,
    YakRemoveRequest,
    YakVoteCreate,
    YakVoteOut,
)

__all__ = [
    # alumni
    "AlumniProfileOut",
    "AlumniProfileUpdate",
    "JobPostCreate",
    "JobPostOut",
    "JobPostUpdate",
    # e2ee
    "DeviceCreate",
    "DeviceOut",
    "DevicePrekeyBundleOut",
    "OneTimePrekeyCreate",
    "OneTimePrekeyOut",
    "PrekeyBundleOut",
    "PrekeyCountOut",
    "PrekeyUpload",
    "PrekeyUploadRequest",
    "SignedPrekeyCreate",
    "SignedPrekeyOut",
    # finance
    "DuesCycleCreate",
    "DuesCycleOut",
    "LedgerEntryCreate",
    "LedgerEntryOut",
    "SpendApprovalCreate",
    "SpendApprovalDecision",
    "SpendApprovalOut",
    "SpendApprovalUpdate",
    # identity
    "CampusOut",
    "ChapterCreate",
    "ChapterInviteCreate",
    "ChapterInviteOut",
    "ChapterJoin",
    "ChapterJoinRequest",
    "ChapterOut",
    "ChapterUpdate",
    "MembershipOut",
    "MembershipUpdate",
    "UserCreate",
    "UserOut",
    "UserUpdate",
    # lineage
    "FamilyCreate",
    "FamilyOut",
    "LineageEdgeCreate",
    "LineageEdgeOut",
    "LineageNodeOut",
    "LineageTreeOut",
    # meetings
    "MeetingAttendanceItem",
    "MeetingAttendanceOut",
    "MeetingAttendanceUpdate",
    "MeetingCreate",
    "MeetingOut",
    "MeetingUpdate",
    # messaging
    "ConversationCreate",
    "ConversationMemberOut",
    "ConversationOut",
    "MessageCreate",
    "MessageOut",
    "MessageReceiptCreate",
    "MessageReceiptOut",
    # social
    "PostCommentCreate",
    "PostCommentOut",
    "PostCreate",
    "PostLikeOut",
    "PostOut",
    "PostUpdate",
    # yak
    "ContentReportCreate",
    "ContentReportOut",
    "UserBlockCreate",
    "UserBlockOut",
    "YakCreate",
    "YakOut",
    "YakRemoveRequest",
    "YakVoteCreate",
    "YakVoteOut",
]
