"""Pydantic v2 request/response schemas, split by domain to mirror app.models."""

from app.schemas.alumni import (
    AlumniProfileOut,
    AlumniProfileUpdate,
    JobPostCreate,
    JobPostOut,
    JobPostUpdate,
)
from app.schemas.e2ee import (
    DeviceCreate,
    DeviceOut,
    DevicePrekeyBundleOut,
    OneTimePrekeyCreate,
    OneTimePrekeyOut,
    PrekeyBundleOut,
    PrekeyCountOut,
    PrekeyUpload,
    PrekeyUploadRequest,
    SignedPrekeyCreate,
    SignedPrekeyOut,
)
from app.schemas.events import (
    EventCreate,
    EventOut,
    EventRsvpOut,
    EventRsvpUpdate,
)
from app.schemas.finance import (
    DuesCycleCreate,
    DuesCycleOut,
    LedgerEntryCreate,
    LedgerEntryOut,
    SpendApprovalCreate,
    SpendApprovalDecision,
    SpendApprovalOut,
    SpendApprovalUpdate,
)
from app.schemas.identity import (
    AttendanceOverview,
    CampusOut,
    ChapterCreate,
    ChapterInviteCreate,
    ChapterInviteOut,
    ChapterJoin,
    ChapterJoinRequest,
    ChapterOut,
    ChapterOverview,
    ChapterUpdate,
    DuesOverview,
    InviteOverview,
    LineageOverview,
    RoleCount,
    RosterOverview,
    MembershipOut,
    MembershipUpdate,
    UserCreate,
    UserOut,
    UserUpdate,
)
from app.schemas.lineage import (
    FamilyCreate,
    FamilyOut,
    LineageEdgeCreate,
    LineageEdgeOut,
    LineageNodeOut,
    LineageTreeOut,
)
from app.schemas.meetings import (
    MeetingAttendanceItem,
    MeetingAttendanceOut,
    MeetingAttendanceUpdate,
    MeetingCreate,
    MeetingOut,
    MeetingUpdate,
)
from app.schemas.messaging import (
    ConversationCreate,
    ConversationMemberOut,
    ConversationOut,
    MessageCreate,
    MessageOut,
    MessageReceiptCreate,
    MessageReceiptOut,
)
from app.schemas.moderation import (
    ContentRemoveRequest,
    ModerationActionOut,
    SuspendUserRequest,
    SuspensionStateOut,
)
from app.schemas.social import (
    FeedPostOut,
    PostCommentCreate,
    PostCommentOut,
    PostCreate,
    PostLikeOut,
    PostOut,
    PostUpdate,
)
from app.schemas.chirp import (
    ContentReportCreate,
    ContentReportOut,
    UserBlockCreate,
    UserBlockOut,
    ChirpCreate,
    ChirpOut,
    ChirpRemoveRequest,
    ChirpVoteCreate,
    ChirpVoteOut,
)

__all__ = [
    # alumni
    "AlumniProfileOut",
    "AlumniProfileUpdate",
    "JobPostCreate",
    "JobPostOut",
    "JobPostUpdate",
    # e2ee
    "DeviceCreate",
    "DeviceOut",
    "DevicePrekeyBundleOut",
    "OneTimePrekeyCreate",
    "OneTimePrekeyOut",
    "PrekeyBundleOut",
    "PrekeyCountOut",
    "PrekeyUpload",
    "PrekeyUploadRequest",
    "SignedPrekeyCreate",
    "SignedPrekeyOut",
    # events
    "EventCreate",
    "EventOut",
    "EventRsvpOut",
    "EventRsvpUpdate",
    # finance
    "DuesCycleCreate",
    "DuesCycleOut",
    "LedgerEntryCreate",
    "LedgerEntryOut",
    "SpendApprovalCreate",
    "SpendApprovalDecision",
    "SpendApprovalOut",
    "SpendApprovalUpdate",
    # identity
    "AttendanceOverview",
    "CampusOut",
    "ChapterCreate",
    "ChapterInviteCreate",
    "ChapterInviteOut",
    "ChapterJoin",
    "ChapterJoinRequest",
    "ChapterOut",
    "ChapterOverview",
    "ChapterUpdate",
    "DuesOverview",
    "InviteOverview",
    "LineageOverview",
    "RoleCount",
    "RosterOverview",
    "MembershipOut",
    "MembershipUpdate",
    "UserCreate",
    "UserOut",
    "UserUpdate",
    # lineage
    "FamilyCreate",
    "FamilyOut",
    "LineageEdgeCreate",
    "LineageEdgeOut",
    "LineageNodeOut",
    "LineageTreeOut",
    # meetings
    "MeetingAttendanceItem",
    "MeetingAttendanceOut",
    "MeetingAttendanceUpdate",
    "MeetingCreate",
    "MeetingOut",
    "MeetingUpdate",
    # messaging
    "ConversationCreate",
    "ConversationMemberOut",
    "ConversationOut",
    "MessageCreate",
    "MessageOut",
    "MessageReceiptCreate",
    "MessageReceiptOut",
    # moderation
    "ContentRemoveRequest",
    "ModerationActionOut",
    "SuspendUserRequest",
    "SuspensionStateOut",
    # social
    "FeedPostOut",
    "PostCommentCreate",
    "PostCommentOut",
    "PostCreate",
    "PostLikeOut",
    "PostOut",
    "PostUpdate",
    # chirp
    "ContentReportCreate",
    "ContentReportOut",
    "UserBlockCreate",
    "UserBlockOut",
    "ChirpCreate",
    "ChirpOut",
    "ChirpRemoveRequest",
    "ChirpVoteCreate",
    "ChirpVoteOut",
]
